php_version: '7.3'
php_default_version_debian: '{{ php_version }}'
php_enable_webserver: false
php_use_managed_ini: false
php_enable_php_fpm: true
php_fpm_listen: "/run/php/php{{ php_version }}-fpm.sock"
php_enable_apc: false
php_opcache_enable: "0"
php_packages:
  - php{{php_version}}-cli
  - php{{php_version}}-fpm
  - php{{php_version}}-common
  - php{{php_version}}-mbstring
  - php{{php_version}}-xml
  - php{{php_version}}-dev
  - php{{php_version}}-zip
  - php{{php_version}}-sqlite3
  - php{{php_version}}-pdo
  - php{{php_version}}-mysql
  - php{{php_version}}-xdebug
  - php{{php_version}}-curl
php_pecl_extensions:
  - rdkafka